/* elf object to shellcode dumper
 *
 * dumps netwide assembler objects to the famous shellcode strings.
 * note that the shellcode has to start at object entry point.
 * 
 * $Id: dumpcode.c,v 1.1.1.1 2006/09/27 10:08:58 roman Exp $
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define CODE_TYPE 1    /* 0 for octal, 1 for hexadecimal */
#define LINE_SIZE 10   /* bytes per line */

static void usage(const char *argv0)
{
  fprintf(stderr, "lame elf object to shellcode dumper\n\n");
  fprintf(stderr, "usage: %s <object>\n\n", argv0);
  fprintf(stderr, "<infile> is an ELF object file generated by NASM\n");
  fprintf(stderr, "output is printed to stdout\n");
  exit(0);
}

int main(int argc, char *argv[])
{
  FILE *in;
  unsigned char codebuf[1024];
  size_t size;
  int index;
  
  if(argc < 2)
    usage(argv[0]);
  
  if(!(in = fopen(argv[1], "r")))
    {
      fprintf(stderr, "couldn't open file '%s'\n", argv[1]);
      exit(0x29a);
    }
  
  fseek(in, 0x0130, SEEK_SET);
  
  printf("static char shellcode[] = \"");
  
  size = fread(codebuf, 1024, 1, in);
  
  for(index = 0; codebuf[index]; index++)
    {
      if(!strncmp(&codebuf[index], "/bin/sh", 7))
        {
          printf("/bin/sh");
          index += 7;
        }
      else
        {
          if(index && !(index % LINE_SIZE))
            printf("\"\n                          \"");
          
          printf( 
#if CODE_TYPE
                  "\\x%02x",
#else
                  "\\%03o",
#endif
           codebuf[index]);
        }      
    }
  
  printf("\";\n");
  
  return 0;
}
