if(CMAKE_C_COMPILER_ID STREQUAL "GNU")

#if(CMAKE_BUILD_TYPE STREQUAL "Debug")
  set(CMAKE_C_FLAGS_DEBUG "-g -ggdb -O0 -Wall")
#elseif(CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
  set(CMAKE_C_FLAGS_RELWITHDEBINFO "-g -ggdb -O2 -Wall")
#elseif(CMAKE_BUILD_TYPE STREQUAL "MinSizeRel")
  set(CMAKE_C_FLAGS_MINSIZEREL "-fomit-frame-pointer -Wall -Os")
#elseif(CMAKE_BUILD_TYPE STREQUAL "Release")
   set(CMAKE_C_FLAGS_RELEASE "-g -Wall -O2")
#endif()

elseif(CMAKE_C_COMPILER_ID STREQUAL "Clang")


  set(CMAKE_C_FLAGS_DEBUG "-g")
  set(CMAKE_C_FLAGS_RELWITHDEBINFO "-g")
  set(CMAKE_C_FLAGS_MINSIZEREL "-Os")
  set(CMAKE_C_FLAGS_RELEASE "-O2")

elseif(CMAKE_C_COMPILER_ID STREQUAL "MSVC")

  set(CMAKE_C_FLAGS_DEBUG "/Z7")
  set(CMAKE_C_FLAGS_RELWITHDEBINFO "/Z7")
  set(CMAKE_C_FLAGS_MINSIZEREL "/Os")
  set(CMAKE_C_FLAGS_RELEASE "/Ox")

endif()
