if(NOT DEFINED DEFAULT_LOADABLE_MODULES)
  set(DEFAULT_LOADABLE_MODULES TRUE)
endif()

if(NOT DEFINED BUILD_LOADABLE_MODULES)
  set(BUILD_LOADABLE_MODULES "${DEFAULT_LOADABLE_MODULES}" CACHE BOOL "Build dynamically loaded modules")
endif(NOT DEFINED BUILD_LOADABLE_MODULES)


