include(FindOpenSSL)

if(OPENSSL_LIBRARY)
  set(USE_OPENSSL true CACHE BOOL "Use OpenSSL")
endif()
if(OPENSSL_FOUND)
  set(USE_OPENSSL true CACHE BOOL "Use OpenSSL")
endif()

if(USE_OPENSSL)
  set(OPENSSL_LIBS "${OPENSSL_SSL_LIBRARY}" "${OPENSSL_CRYPTO_LIBRARY}")
  include_directories(${OPENSSL_INCLUDE_DIR})
  set(HAVE_OPENSSL 1)
  add_definitions(-DHAVE_SSL=1)
  set(OPENSSL_LIBRARY "${OPENSSL_LIBRARIES}")

  string(REGEX REPLACE "lib\/.*" "lib" OPENSSL_LIBDIR "${OPENSSL_LIBRARY}")
  message(STATUS "Got OpenSSL:\n  OPENSSL_INCLUDE_DIR = ${OPENSSL_INCLUDE_DIR}\n  OPENSSL_LIBRARIES = ${OPENSSL_LIBRARIES}\n  OPENSSL_LIBDIR = ${OPENSSL_LIBDIR}")

  set(CMAKE_INSTALL_RPATH "${OPENSSL_LIBDIR}:${CMAKE_INSTALL_PREFIX}/lib")
endif()

